name: Opdater priser

on:
  schedule:
    - cron: '*/30 * * * *'  
  workflow_dispatch:

jobs:
  update-priser:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Tjekk repo ud
        uses: actions/checkout@v3
        with:
          persist-credentials: false  

      - name: Opsæt Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Installer dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests tqdm

      - name: Kør dba.py
        run: python scripts/dba.py

      - name: Commit og push opdateret priser.json.gz
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/priser.json.gz
          git diff --staged --quiet || git commit -m "Automatisk opdatering af priser.json.gz"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/UmFzbXVz/gg.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
