name: Opdater priser

on:
  schedule:
    - cron: '*/30 * * * *'   
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Tjekk repo ud
      uses: actions/checkout@v3

    - name: Opsæt Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Installer dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests tqdm

    - name: Kør dba.py
      run: |
        python scripts/dba.py
        # Sikrer at docs/ findes
        mkdir -p docs
        # Hvis filen ikke blev oprettet af dba.py, opret tom gzip-fil
        if [ ! -f docs/priser.json.gz ]; then
          echo "{}" | gzip > docs/priser.json.gz
        fi
        ls -l docs/

    - name: Commit og push opdateret priser.json.gz
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs/priser.json.gz
        git diff --staged --quiet || git commit -m "Automatisk opdatering af priser.json.gz"
        git push
